### ISSUE TITLE
installation with yajl plugin

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/homebrew-elektra#1]
I tried installing elektra with the yajl plugin on a fresh macOS installation via:

```
brew tap ElektraInitiative/homebrew-elektra
brew install yajl elektra
```

but it does not seem to install elektra with the yajl plugin:

```
kdb list | grep yajl
```

(no output)

**Comment by sanssecours** [comment]
Thank you for the input! You need to use the switch `--with-dep-plugins` to also install the `yajl` plugin:

```sh
brew install elektra --with-dep-plugins
```

. Unfortunately this does not work currently though, since there are problems in the CMake code of the Augeas plugin:

```
CMake Error at cmake/Modules/LibAddPlugin.cmake:185 (message):
  Internally inconsistency, plugin elektra-augeas got different values for
  variable ARG_LINK_LIBRARIES: '/usr/local/lib/libaugeas.dylib' !=
  '/usr/local/lib/libaugeas.dylib;/usr/lib/libxml2.dylib'
Call Stack (most recent call first):
  cmake/Modules/LibAddPlugin.cmake:241 (restore_variable)
  src/plugins/augeas/CMakeLists.txt:28 (add_plugin)
  src/plugins/CMakeLists.txt:14 (include)
```

. I already opened a pull request about this issue [here](https://github.com/ElektraInitiative/libelektra/pull/1761). If the PR fixes the problem, then you should be able to install the `yajl` plugin via

```sh
brew install elektra --with-dep-plugins --HEAD
```

, after we merge the changes into the master branch of [`ElektraInitiative/libelektra`](https://github.com/ElektraInitiative/libelektra).

By the way, if you want more information about the available options of the formula, you can always use `brew info`:

```sh
brew info elektra
#> elektrainitiative/elektra/elektra: stable 0.8.21 (bottled), HEAD
#> Configuration Framework
#> https://libelektra.org
#> Not installed
#> From: https://github.com/ElektraInitiative/homebrew-elektra/blob/master/Formula/elektra.rb
#> ==> Dependencies
#> Build: cmake ✔, doxygen ✔
#> Optional: augeas ✔, dbus ✔, libgit2 ✔, boost ✔, yajl ✔, yaml-cpp ✔, lua ✔, qt ✔
#> ==> Options
#> --with-dep-plugins
#> 	Build with additional plugins: augeas, dbus, gitresolver, tcl, yajl, yamlcpp
#> --with-lua
#> 	Build with lua support
#> --with-qt
#> 	Build GUI frontend
#> --HEAD
#> 	Install HEAD version
```

.

**Comment by sanssecours** [comment]
Installation of Elektra together with the `yajl` plugin should now work again, if you use the following commands:

```sh
brew install yajl
brew tap ElektraInitiative/homebrew-elektra
brew install elektra --with-dep-plugins --HEAD
```

.

**Comment by omnidan** [comment]
@sanssecours I tried that but am getting the following warning:

```
Warning: elektra: this formula has no --with-dep-plugins option so it will be ignored!
```

**Comment by sanssecours** [comment]
I guess you are using the [new Homebrew formula](https://github.com/Homebrew/homebrew-core/pull/22049) from [`homebrew-core`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/elektra.rb). If you want to install the formula from this tap you need to state so [explicitly](https://github.com/ElektraInitiative/homebrew-elektra#installation):

```
brew install elektrainitiative/elektra/elektra --with-dep-plugins
```

.
